### ISSUE TITLE
Issue with basic functionality

### ISSUE THREAD

**Issue by Yeok-c** [yudarw/CoppeliaSim-UR10-with-Python#1]
Hi, thanks for the great work! I'm trying to just run the test.py, but it moves to the first point and stops. It seems like it never breaks out of the while loop of self.isMoving() from here

```
    def set_position2(self, pos, wait):
        self.set_position(pos)
        if wait:
            while True:
                time.sleep(0.05)
                if self.isMoving() == 'NOT_MOVING':
                    break
        print(f"Moved to position {pos}")
```

of which when I checked the (ret, s) from here,
```
    def isMoving(self):
        ret, s = sim.simxGetStringSignal(self.clientID, 'test_signal', sim.simx_opmode_buffer)
        s = s.decode('ascii')
        print(f"ret: {ret}, s: {s}")
        return s
```
I get output:
ret: 8, s: 
ret: 8, s: 
ret: 8, s: 
ret: 8, s: 
ret: 8, s: 
ret: 8, s: 
ret: 8, s: 
ret: 8, s: 
ret: 8, s: 

It does not change before or after the it reaches the first point.

My questions:
1. Which version of CoppeliaSim are you using? Perhaps I should match your version.
2. Do you have any clues as to why it is happening? 

Thanks!

**Comment by yudarw** [comment]
Hi, thank you for the feedback. Yes, you're right. The robot stuck after the first point is because the robot is waiting for the moving signal. It is because I forget to update the script in the scene.
The loop part of the UR10 inside the simulation script is look like this. The trigger is using the `int32` signal instead of  `string` signal. 
```
while true do
        if moveIkMode then
            moveIkMode=false
            sim.setInt32Signal(movingSignalName,1)
            pose = convertToPose2(targetPos, targetOri)
            moveToPose_viaIK(ikMaxVel,ikMaxAccel,ikMaxJerk,pose,data)
            sim.setInt32Signal(movingSignalName,0)
        end
        
        if moveJointMode then
            moveJointMode=false
        end
    end 
```

So, you can the `Robot.isMoving()` method `coppeliasim.py` as follows:
```
# Check whether the robot is moving
    def isMoving(self):
        ret, s = sim.simxGetInt32Signal(self.clientID, 'moving_status', sim.simx_opmode_buffer)
        return s
```

After that, check the moving status to wait the robot to complete the movement.
```
def set_position2(self, pos, wait):
        self.set_position(pos)
        if wait:
            while True:
                time.sleep(0.1)
                if self.isMoving() == 0:
                    break
```

**Comment by yudarw** [comment]
close
